#!/bin/bash

#remove 0 directory
rm -fR 0

#create 0 directories
mkdir 0
mkdir 0/JSAV

#copy exercises and lib directories from master
git checkout master -- exercises
git checkout master -- lib

#move directories
git mv exercises 0
git mv lib 0

#build JSAV
cd JSAV
make
cd ..

#copy necessay JSAV files
cp -r JSAV/build 0/JSAV
cp -r JSAV/css 0/JSAV
cp -r JSAV/extras 0/JSAV
cp -r JSAV/lib 0/JSAV

git add 0/JSAV

echo Done! Ready to commit changes!
